[package]
name = "mnemonist"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
indexmap = { version = "2.2.6", features = ["serde"] }
napi = { version = "2.16.17", optional = true, features = ["serde-json"] }
napi-derive = { version = "2.16.13", optional = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[target.'cfg(unix)'.dependencies]
http-body-util = { version = "0.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
vercel_runtime = { version = "2.4.0", optional = true }

[[bin]]
name = "protocol"
path = "api/protocol.rs"
required-features = ["web"]

[[bin]]
name = "health"
path = "api/health.rs"
required-features = ["web"]

[features]
default = ["web"]
nodejs = ["napi", "napi-derive"]
web = ["dep:http-body-util", "dep:tokio", "dep:vercel_runtime"]
