[package]
name = "mnemonist"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
indexmap = { version = "2.2.6", features = ["serde"] }
napi = { version = "2.16.17", optional = true, features = ["serde-json"] }
napi-derive = { version = "2.16.13", optional = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[features]
default = []
nodejs = ["napi", "napi-derive"]
